name: Deploy App

on:
  workflow_call: 
    inputs:
      env:
        description: environment
        required: true
        type: string
      artifact_name:
        description: artifact name
        required: true
        type: string
      
jobs:

  task1:
    runs-on: ubuntu-latest   
    environment: ${{ inputs.env }}          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build       
