name: detect-environment

on:
  workflow_call: 
    inputs:
      branch: 
        type: string
        required: true
        description: branch of event 
 
jobs:
  

  task1:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:    

      - name: Determine Environment
        id: set-env
        run: |
          if [ "${{ inputs.branch }}" == "refs/heads/main" ]; then
            echo "environment=production" > $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi                
