name: Deploy React APp

on:
  push:
    branches:
      - main
      - staging

jobs:
  
  build:
    uses: ./.github/workflows/generateArtifact.yml
    with:
      use-cache: true


  detect-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:    

      - name: Determine Environment
        id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment=production" > $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi                



  deploy:
    runs-on: ubuntu-latest
    needs: [detect-environment,build]
    environment: ${{ needs.detect-environment.outputs.environment }}  # Usamos el entorno calculado en detect-environment            
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build       
