name: Deploy React APp

on:
  workflow_call:     
  workflow_dispatch: 

jobs:
  detect-environment:
    uses: ./.github/workflows/detectEnvWF.yml
    with:
      branch: ${{github.ref}}    
  
  build:
    uses: ./.github/workflows/buildWF.yml

  deploy:
   needs: [build,detect-environment]
   uses: ./.github/workflows/deployWF.yml
   with:
     env: ${{needs.detect-environment.outputs.environment}}
     artifact_name: ${{needs.build.outputs.artifact_name}}
